export const MAIN_URL =  'https://shortletrental.com'
// export const MAIN_URL =  'http://153.92.4.13/shortlet'

export const BASE_URL =  MAIN_URL+'/api/auth'
// export const BASE_URL =  'https://zea-virtual-events.com/shortletrental/api/auth'

export const HOME_URL = `${BASE_URL}/getHomeData1`
export const HOME_URL1 = `${BASE_URL}/propertyList`
export const PROPERTYLIST = `${BASE_URL}/propertyList`
export const Login_Url = `${BASE_URL}/login`
export const Sign_UP = `${BASE_URL}/signUp`
export const Change_Password = `${BASE_URL}/change-password`
export const Send_Otp = `${BASE_URL}/send-otp`
export const Verify_Otp = `${BASE_URL}/verify-otp`
export const Update_Profile = `${BASE_URL}/update-profile`
export const Logout = `${BASE_URL}/logout`
export const add_To_Favourite = `${BASE_URL}/addToWishList`
export const my_favorites = `${BASE_URL}/my_favorites`
export const Home_Details = `${BASE_URL}/propertyDetails`
export const AddToCart = `${BASE_URL}/store-card`
export const get_store_card = `${BASE_URL}/get_store_card`
export const Default_Card = `${BASE_URL}/defaultCard`
export const Update_Card = `${BASE_URL}/update_card`
export const Delete_Card = `${BASE_URL}/deleteCard`
export const Forgot_Password = `${BASE_URL}/forgot-password`
export const Reset_Password = `${BASE_URL}/reset-password`
export const Booking = `${BASE_URL}/mobileBooking`
export const BookingCheckout = `${BASE_URL}/checkout`
export const ReserveCheckout = `${BASE_URL}/checkout_reserve`
export const ReserveFromCheckout = `${BASE_URL}/checkout_from_reserve`
export const getReserveList = `${BASE_URL}/getreservations`
export const getAllCountry = `${BASE_URL}/getAllCountry`
export const getAllProvince = `${BASE_URL}/getAllProvince`
export const getAllProvince1 = `${BASE_URL}/getAllProvince1`
export const getAllCity = `${BASE_URL}/getAllCity`
export const getAllArea = `${BASE_URL}/getAllArea`
export const getCityArea = `${BASE_URL}/getCityArea`
export const getOffer = `${BASE_URL}/getOffer`
export const getAllCategory = `${BASE_URL}/getAllCategory`
export const checkCouponCode = `${BASE_URL}/checkCouponCode`
export const getOfferDetailApiUse = `${BASE_URL}/OfferDetail`
export const getAllServicesApiUse = `${BASE_URL}/getAllServices`
export const getBooking = `${BASE_URL}/getbookings`
export const cancelBooking = `${BASE_URL}/cancelBooking`
export const starRating = `${BASE_URL}/submit-rate`
export const bookingDetail = `${BASE_URL}/bookingDetail`
export const User_Profile = `${BASE_URL}/user-profile`
export const Royalty_Points = `${BASE_URL}/royalty-points`
export const getAllProperty = `${BASE_URL}/getAllCategory`
export const Contact_Url = `${BASE_URL}/updateContactDetails`
export const Notification_Count = `${BASE_URL}/notification-count`
export const Notification_List = `${BASE_URL}/notification-list`
export const Notification_Remove = `${BASE_URL}/notification-remove`
export const Notification_Read = `${BASE_URL}/read-notification`
export const ChatApi = `${BASE_URL}/chat-list`
export const GoogleSocialLogin = `${BASE_URL}/mobileSocialLogin`
export const Chat_Details = `${BASE_URL}/chat-detail`
export const getAllTypes = `${BASE_URL}/getAllTypes`
export const becomeahost_signUp = `${BASE_URL}/becomeahost_signUp`
export const getAllAmenities = `${BASE_URL}/getAllAmenities`
export const getPropertyMinMaxPrice = `${BASE_URL}/getPropertyMinMaxPrice`
export const getAllServices = `${BASE_URL}/getAllServices`
export const becomeahost_add_property = `${BASE_URL}/becomeahost_add_property`
export const Schedule_Event = `${BASE_URL}/schedule_appointment`
export const Share_Booking = `${BASE_URL}/share-booking`
export const Booking_Reserve = `${BASE_URL}/mobileBookingReserve`
export const getBooking_Reserve = `${BASE_URL}/getMobileBookingReserve`
export const propertyBookingCalender = `${BASE_URL}/propertyDetailsBookingDates`
export const Notification_On_OFF = `${BASE_URL}/notificationOnOff`
export const AddProvince = `${BASE_URL}/addProvince`
export const AddCity = `${BASE_URL}/addCity`
export const AddArea = `${BASE_URL}/addArea`
export const AddCartBooking = `${BASE_URL}/add-cart`
export const GetCartBooking = `${BASE_URL}/get-cart`
export const BookingVerify = `${BASE_URL}/booking-verify`
export const getCartReserve = `${BASE_URL}/get-resv_booking`
export const checkOutFromReserve = `${BASE_URL}/checkout_from_reserve`




// export const CREATE_ACCESS_TOKEN = 'https://accounts.accesscontrol.windows.net/33ec418b-9776-46f1-9cff-c19495bd02f2/tokens/OAuth/2'
// export const CREATE_NEW_USER = `${BASE_URL}GetByTitle('Users')/items`
// export const EVENTS = `${BASE_URL}getbytitle('Events')/items`
// export const PROPERTIES = `${BASE_URL}getbytitle('Barwa’s Properties')/items`

// export const EVENTSCATEGORIES = `${BASE_URL}getbytitle('Property Primary Categories')/items`
// export const EVENTSCATEGORIESSECONDORY = `${BASE_URL}getbytitle('Property Secondary Categories')/items`

// export const FEATUREDPROPERTIES = `${BASE_URL}getbytitle('Barwa’s Properties')/items`
// export const ONGOINGPROJECTS = `${BASE_URL}getbytitle('Barwa’s Projects')/items`
// // export const GETAGENTDETAILS = `${BASE_URL}getbytitle('Contact Agents')/items`
// // export const GETLOCATIONBYID = `${BASE_URL}getbytitle('Barwa Parking Locations')/items`
// export const OUTLETS = `${BASE_URL}getbytitle('Barwa’s Outlets')/items`
// export const SEARCH_PROPERTY = `${BASE_URL}GetByTitle('Barwa’s Properties')/items`
// export const FILTER_PROPERTY = `${BASE_URL}getbytitle('Property Filters')/items`
// export const GETPARKINGDETAILS = `${BASE_URL}getbytitle('Barwa Parking Locations')/items`
// export const GETSCHEDULETIME = `${BASE_URL}getbytitle('Parking Booking Schedule')/items`
// export const BOOKCAR = `${BASE_URL}GetByTitle('Car Parking Bookings')/items`