const Images = {
    fbIcon:require('./../assets/images/fbIcon.png'),
    beforIcon:require('./../assets/images/befor.png'),
    xmark:require('./../assets/images/x-mark.png'),
    homeIcon:require('./../assets/images/whiteHome.png'),
    checkIcon:require('./../assets/images/checkMark.png'),
    checkblank:require('./../assets/images/recblack.png'),
    checkfull:require('./../assets/images/redcheck.png'),
    rightIcon:require('./../assets/images/right.jpg'),
    radioActivesIcon:require('./../assets/images/radioactive.png'),
    radioinactiveIcon:require('./../assets/images/radioinactive.png'),
    deleteIcon:require('./../assets/images/delete.png'),
    BackgroundImage:require('./../assets/images/BackgroundImage.png'),
    plusImage:require('./../assets/images/duplicate.png'),
    MaskImage:require('./../assets/images/Mask.png'),
    emptyStarImage:require('./../assets/images/star3.png'),
    radioImage:require('./../assets/images/radio.png'),
    dislikeradioImage:require('./../assets/images/radio-button.png'),
    featureImage:require('./../assets/images/Feature.png'),
    plusIcon:require('./../assets/images/plus.png'),
    minusIcon:require('./../assets/images/minus-sign.png'),
    whiteImage:require('./../assets/images/whiteImage.png'),
    House:require('./../assets/images/House.png'),
    whiteDot:require('./../assets/images/whiteDotScroll.png'),
    mobileIcon:require('./../assets/images/mobileIcons.png'),
    appleIcon:require('./../assets/images/appleIcon.png'),
    googleIcon:require('./../assets/images/googleIcon.png'),
    calenderIcon:require('./../assets/images/calenderIcon.png'),
    BeachTableIcon:require('./../assets/images/BeachTableIcons.jpg'),
    ChairIcon:require('./../assets/images/ChairIcon.jpg'),
    SwimingPoolIcon:require('./../assets/images/SwimingPoolIcon.jpg'),
    TinyHouseIcon:require('./../assets/images/TinyHouseIcon.jpg'),
    TreeHouseIcon:require('./../assets/images/TreeHouseIcon.jpg'),
    TreeIcon:require('./../assets/images/TreeIcon.jpg'),
    RecievedMoney:require('./../assets/images/recievePoint.png'),
    SendMoney:require('./../assets/images/sendPoint.png'),
    HeartNotSelectedIcon:require('./../assets/images/1814104_favorite_heart_like_love_icon.png'),
    FeaturedIcons:require('./../assets/images/FeaturedIcons.png'),
    GroupIcons:require('./../assets/images/profile.png'),
    DotIcon:require('./../assets/images/dots.png'),
    No_Data:require('./../assets/images/no-data-found.png'),
    // GroupIcons:require('./../assets/images/Bed.svg'),
    heart:require('./../assets/images/love.png'),
    LocationIcons:require('./../assets/images/locations.png'),
    NotificationIcons:require('./../assets/images/NotificationIcons.png'),
    ProfileIcons:require('./../assets/images/ProfileIcons.png'),
    messageIcons : require('./../assets/images/emails.png'),
    email : require('./../assets/images/email.png'),
    uploadIcon : require('./../assets/images/upload.png'),
    PlusIcon : require('./../assets/images/kamal.png'),
    SplashIcon : require('./../assets/images/Group895.png'),
    messageIcon : require('./../assets/images/message.png'),
    activeIcon : require('./../assets/images/Active.png'),
    inActiveIcon : require('./../assets/images/Inactive.png'),
    plusIcon : require('./../assets/images/plusIcon.png'),
    minusIcon : require('./../assets/images/minusIcon.png'),
    hiddenIcon : require('./../assets/images/hidden.png'),
    eyeIcon : require('./../assets/images/view.png'),
    rightSignIcon : require('./../assets/images/rightSign.png'),
    
    crossIcon : require('./../assets/images/cross.png'),
    slider : require('./../assets/images/slider.jpg'),
    hostimg : require('./../assets/images/host_img.jpg'),
   
    SeekLogoIcons:require('./../assets/images/SeekLogoIcons.png'),
    StartIcon:require('./../assets/images/StartIcon.png'),
    StartBigIcon:require('./../assets/images/starg.png'),
    StarIcon:require('./../assets/images/star.png'),
    BedIcons:require('./../assets/images/bedroom.png'),
    ProfileImageIcons:require('./../assets/images/ProfileImageIcons.png'),

    ArrowIcons:require('./../assets/images/ArrowIcons.png'),
    arrIcon:require('./../assets/images/arrIcon.png'),
    DownArrow:require('./../assets/images/down-arrow.png'),
    BioMetric:require('./../assets/images/BioMetric.png'),
    Chevron_Right:require('./../assets/images/Chevron_Right.png'),
    Chats:require('./../assets/images/Chats.png'),
    Filters:require('./../assets/images/Filters.png'),
    SearchOrangeIcons:require('./../assets/images/SearchOrangeIcons.png'),
    OrangeIcons:require('./../assets/images/orangeSearch.png'),
    Solid:require('./../assets/images/Solid.png'),
    chairSelectedIcon:require('./../assets/images/chairSelectedIcon.png'),
    HeaderImage:require('./../assets/images/HeaderImage.png'),
    HotelImage:require('./../assets/images/HotelImage.png'),
    Broze:require('./../assets/images/Broze.png'),
    ShareIcons:require('./../assets/images/ShareIcons.png'),
    selectedIcons:require('./../assets/images/selectedIcons.png'),
    UploadIcons:require('./../assets/images/UploadIcons.png'),
    heartIcon :require('./../assets/images/heartIcon.png'),
    CallIcons :require('./../assets/images/CallIcons.png'),
    LocationIcon :require('./../assets/images/LocationIcon.png'),
    CardDesignIcon :require('./../assets/images/CardDesignIcon.png'),
    cardTypeIcon :require('./../assets/images/cardTypeIcon.png'),
    deleteIcon :require('./../assets/images/deleteIcon.png'),
    deleteSliderIcon :require('./../assets/images/deleteSlider.png'),
    EditCardIcon :require('./../assets/images/EditCardIcon.png'),
    LeftSideIcon :require('./../assets/images/LeftSideIcon.png'),
    RightSideIcon :require('./../assets/images/RightSideIcon.png'),
    notification :require('./../assets/images/notification.png'),
    notificationUnselectedIcon :require('./../assets/images/notificationUnselectedIcon.png'),
    pfofile :require('./../assets/images/pfofile.png'),
    EyeIcons :require('./../assets/images/EyeIcons.png'),
    SearchIcons:require('./../assets/images/SearchIcons.png'),
    unFavoriteIcon: require('./../assets/images/unFavoriteIcon.png'),
    GirlImageIcon: require('./../assets/images/GirlImageIcon.png'),
    DottedRectangleIcon: require('./../assets/images/DottedRectangleIcon.png'),
    BlueDotIcons:require('./../assets/images/BlueDotIcons.png'),
    cancelImageIcon:require('./../assets/images/cancelImageIcon.png'),
    House1:require('./../assets/images/house1.png'),
    House2:require('./../assets/images/house2.png'),
    House3:require('./../assets/images/house3.png'),
    House4:require('./../assets/images/house4.png'),
    House5:require('./../assets/images/house5.png'),
    House6:require('./../assets/images/house6.png'),
    BecomeIcon:require('./../assets/images/BecomeIcon.png'),
    BecomeIcon:require('./../assets/images/BecomeIcon.png'),
    RectangleUpload:require('./../assets/images/RectangleUpload.png'),
    AnimalIcon:require('./../assets/images/AnimalIcon.png'),
    CameraIcon:require('./../assets/images/CameraIcon.png'),
    WeaponIcon:require('./../assets/images/WeaponIcon.png'),
    OrangeDotIcon:require('./../assets/images/OrangeDotIcon.png'),
    SmallOrangeDotIcon:require('./../assets/images/SmallOrangeDotIcon.png'),
    BalconyIcon:require('./../assets/images/BalconyIcon.png'),
    KitchenIcon:require('./../assets/images/KitchenIcon.png'),
    PrivateBackyardIcon:require('./../assets/images/PrivateBackyardIcon.png'),
    WifiIcon:require('./../assets/images/WifiIcon.png'),
    OceanView:require('./../assets/images/OceanView.png'),
    youngBoyIcon:require('./../assets/images/youngBoyIcon.png'),
    checkMarkIcon:require('./../assets/images/checkMarkIcon.png'),
    AirConditionerIcon:require('./../assets/images/AirConditionerIcon.png'),
    noStar:require('./../assets/images/nostar.png'),
    oneStar:require('./../assets/images/1star.png'),
    twoStar:require('./../assets/images/2star.png'),
    threeStar:require('./../assets/images/3star.png'),
    fourStar:require('./../assets/images/4star.png'),
    fiveStar:require('./../assets/images/5star.png'),
    supertag:require('./../assets/images/superhosttag.png'),
    luxurytag:require('./../assets/images/luxurytag.png'),
    raretag:require('./../assets/images/raretag.png'),
    beforeHome:require('./../assets/images/before-home.png'),
}


export default Images;